import java.awt.Color;
import java.awt.Container;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
 
public class NullLayout extends JFrame {
 
     /**
	 * Autogenerated serialized identifier
	 */
	private static final long serialVersionUID = 1L;
	private JButton jb0, jb1, jb2, jb3, jb4, jb5, jb6, jb7, jb8, jb9;
	private JLabel label;
	boolean isTrue;

	public NullLayout() {
		// TODO Auto-generated constructor stub

		isTrue=true;
		JPanel mainPanel = new JPanel();//Base panel definition
		mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.Y_AXIS));
		add(mainPanel);
		setTitle("Nomis");
		setSize(new Dimension(1000, 600));
		setLocationRelativeTo(null);
		setDefaultCloseOperation(EXIT_ON_CLOSE);

		label = new JLabel();
                
        //TODO Changed filepaths to relative paths instead of absolute paths.        

		Container c = getContentPane();
		c.setLayout(null);
		ImageIcon image0 = new ImageIcon("resources/icons/0.jpg");
		jb0 = new JButton();
		jb0.setIcon(image0);
		ImageIcon image1 = new ImageIcon("resources/icons/1.jpg");
		jb1 = new JButton("1");
		jb1.setIcon(image1);
		ImageIcon image2 = new ImageIcon("resources/icons/2.jpg");
		jb2 = new JButton("2");
		jb2.setIcon(image2);
		ImageIcon image3 = new ImageIcon("resources/icons/3.jpg");
		jb3 = new JButton("3");
		jb3.setIcon(image3);
		ImageIcon image4 = new ImageIcon("resources/icons/4.jpg");
		jb4 = new JButton("4");
		jb4.setIcon(image4);
		ImageIcon image5 = new ImageIcon("resources/icons/5.jpg");
		jb5 = new JButton("5");
		jb5.setIcon(image5);
		ImageIcon image6 = new ImageIcon("resources/icons/6.jpg");
		jb6 = new JButton("6");
		jb6.setIcon(image6);
		ImageIcon image7 = new ImageIcon("resources/icons/7.jpg");
		jb7 = new JButton("7");
		jb7.setIcon(image7);
		ImageIcon image8 = new ImageIcon("resources/icons/8.jpg");
		jb8 = new JButton("8");
		jb8.setIcon(image8);
		ImageIcon image9 = new ImageIcon("resources/icons/9.jpg");
		jb9 = new JButton("9");
		jb9.setIcon(image9);

		jb0.addActionListener(new ActionListener(){
			public void actionPerformed(ActionEvent arg0) {
				if(isTrue){
					label.setText("String 0");
					isTrue=!isTrue;

				}

			}
		});

		jb1.addActionListener(new ActionListener(){
			public void actionPerformed(ActionEvent arg0) {
				if(isTrue){
					label.setText("String 1");
					isTrue=!isTrue;

				}

			}
		});

		jb2.addActionListener(new ActionListener(){
			public void actionPerformed(ActionEvent arg0) {
				if(isTrue){
					label.setText("String 2");
					isTrue=!isTrue;}

				else{isTrue=!isTrue;}

			}
		});

		jb3.addActionListener(new ActionListener(){
			public void actionPerformed(ActionEvent arg0) {
				if(isTrue){
					label.setText("String 3");
					isTrue=!isTrue;

				}

			}
		});

		//Parameters for the x coordinate, y coordinate, width, high

		//TODO instead of setting manual bounds look into finding a grid and using locations of the
		//TODO grid to fit the image in there. 

		jb0.setBounds(0, 0, 130, 130);
		c.add(jb0);

		jb1.setBounds(130, 0, 130, 130);
		c.add(jb1);

		jb2.setBounds(260,0, 130, 130);
		c.add(jb2);

		jb3.setBounds(0, 130, 130, 130);
		c.add(jb3);

		jb4.setBounds(130, 130, 130, 130);
		c.add(jb4);


		jb5.setBounds(260, 130, 130, 130);
		c.add(jb5);

		jb6.setBounds(0, 260, 130, 130);
		c.add(jb6);

		jb7.setBounds(130, 260 , 130, 130);
		c.add(jb7);

		jb8.setBounds(260, 260, 130, 130);
		c.add(jb8);

		jb9.setBounds(0, 400, 390, 130);
		c.add(jb9);

		label.setBounds(180,550,100,30);
		c.add(label);

		setSize(400, 650);
		setVisible(true);
		//Close the window, close the running program
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	}
 
	public static void main(String[] args) {
		new NullLayout();
	}
}